# coding: utf-8
import random

import pandas as pd

filter_step_dict = {
    'filter_resident_city_control_group_inshop_assign': '过滤远距离订单驻城对照组的订单',
    'filter_not_in_queue_v2_transporter_inshop_assign': '过滤离队和休息的骑士',
    'filter_general_direct_order_transporter': '过滤直送订单',
    'filter_health_certificate_order_transporter': '过滤无健康证骑士',
    'filter_long_waiting_time_transporter_inshop_assign': '过滤等单时间过长的骑士(从接第一单开始计时)',
    'filter_low_same_way_score_order_group_inshop_assign': '过滤不顺路的订单组(暂不生效)',
    'filter_trans_sup_path_dis_inshop_assign': '过滤取货距离远的骑士',
    'filter_no_onhands_order_transporter_inshop_assign': '抢单模式下兜底订单过滤休息中骑士',
    'filter_opposite_region_order_transporter': '过滤互斥片区的骑士',
    'filter_last_fetch_short_deliver_ahead_transporter_inshop_assign': '提前派单过滤超时的骑士',
    'filter_ahead_dispatch_inshop_assign': '提前派单过滤',
    'filter_different_region_order_transporter': '过滤不同片区的订单',
    'filter_after_sales_order_transporter': '过滤售后单',
    'filter_crowd_assign_transporter_low_price_order': '过滤低性价比订单-测试',
    'filter_accept_cost_status_error': '过滤计算顺路信息时出错的骑士',
    'filter_same_way_rule_four_inshop_assign': '过滤不顺路的骑士(暂不生效)',
    'filter_crowd_assign_transporter_black_receiver_order': '过滤黑名单收货区域订单-测试',
    'filter_bill_dispatched_transporter_inshop_assign': '过滤5分钟内派过的骑士',
    'filter_cake_transporter': '蛋糕订单过滤非蛋糕骑士',
    'filter_low_grade_transporter': '保价订单过滤白银以下骑士',
    'filter_not_three_party_inshop_transporter_inshop_assign': '驻店订单过滤非三方驻店骑士',
    'filter_not_validation_status_transporter': '过滤认证状态审核未通过的骑士',
    'filter_onhands_unpicked_assign_num': '过滤手头未取货专享单量超过阈值的骑士',
    'filter_order_dispatched_transporter_inshop_assign': '重抛到家订单过滤派过的骑士',
    'filter_out_circle_order_inshop_assign': '过滤圈外订单',
    'filter_first_long_distance_transporter_inshop_assign': '远单过滤空单骑士',
    'filter_queue_transporter_inshop_assign': '有更合适的骑士已派单',
    'filter_ranker_transporter_inshop_assign': '有更合适的骑士已派单',
    'filter_deliver_delay_after_transporter_inshop_assign': '过滤送货超时的骑士',
    'filter_back_and_forth_fetch_transporter_inshop_assign': '过滤折返取货的骑士',
    'filter_back_fetch_transporter_inshop_assign': '过滤折返取货骑士',
    'filter_order_limit_transporter_inshop_assign': '过滤达到最大接单数的骑士',
    'filter_invalid_work_mode_transporter': '过滤工作模式不是驻店模式的骑士',
    'filter_in_forbidden_area_order_inshop_assign': '过滤黑名单区域的订单',
    'filter_location_info_error_inshop_assign': '过滤当前未上传坐标的骑士',
    'filter_dispatched_transporter': '过滤n分钟内派过该单的骑士',
    'filter_total_cargo_weight_transporter_inshop_assign': '过滤达到最大接单重量的骑士',
    'filter_pickup_delay_after_transporter_inshop_assign': '过滤取货超时的骑士',
    'filter_not_in_queue_transporter_inshop_assign': '过滤离队的骑士',
    'filter_resting_transporter_inshop_assign': '过滤休息的骑士',
    'filter_angle_transporter': '过滤与手头订单方向不一致的骑士',
    'filter_minute_dispatch_num': '过滤每分钟派单数达到最大值的骑士',
    'filter_new_dada_ranker_step_transporter': '该单附近有新骑士(新骑士具有优先推荐权)',
    'filter_not_dj_show_transporter': '过滤不展示京东到家订单的骑士',
    'filter_back_haul': '过滤超过回程单距离的骑士',
    'filter_accept_time_delay_transporter': '过滤手头订单存在送达超时的骑士',
    'filter_order_auth_transporter': '过滤手头订单达到最大接单权限的骑士',
    'filter_order_auth': '追单过滤不能接该订单的骑士',
    'filter_direct_order_transporter': '过滤手头有直送订单的骑士',
    'filter_coordinate_error': '检测到骑士有坐标偏移',
    'filter_credit_transporter': '高价值订单过滤非信用骑士',
    'filter_has_task_transporter': '该单为直送订单，过滤手头有单的骑士',
    'filter_inshop_transporter': '过滤驻店骑士',
    'filter_blacklist': ' 过滤在商户黑名单列表中的骑士',
    'filter_cancel_order_filter_transporter': ' 过滤取消订单被拉黑的骑士',
    'filter_over_river_transporter': '过滤取货跨江的骑士',
    'filter_coffee_ranker_step_transporter': '该单附近有咖啡骑士(咖啡骑士具有优先推荐权)',
    'filter_distance_preference': '骑士app设置距离偏好过滤',
    'filter_ranker_step_transporter': '过滤打分排名靠后的骑士',
    'filter_only_dj_show_transporter': '过滤只展示京东到家订单的骑士',
    'filter_onhands_order_invalid_status': '过滤手头订单信息获取失败的骑士',
    'filter_transporter_assign_today_num': '过滤当天专享单数超过限制骑士',
    'filter_transporter_today_not_accept_order_yet': '专享过滤当天尚未接单骑士',
    'filter_onhands_assign_num': '过滤当前手头专享单量超过限制骑士',
    'filter_onhands_num': '过滤当前手头单量超过限制骑士',
    'filter_assigned_transporter': '过滤取消过该订单的骑士',
    'filter_actual_pick_up_distance_vip_assign': '取货距离远过滤',
    'filter_cheat_transporter': '首轮推单过滤外挂可能性高的骑士',
    'filter_not_authorized_transporter': '过滤当前没有接此单权限的骑士',
    'filter_long_distance_strategy_transporter_inshop_assign': '门店组维度远单派单限制',
    'filter_trans_sup_map_distance': '过滤取货距离远的骑士',
    'filter_fake_inshop_transporter_v2': '伪驻店骑士延迟推单',
    'filter_overflow_to_crowd_inshop_assign': '优先溢出众包过滤',
    'filter_assign_interval': '专享派单间隔过滤',
    'filter_vip_assign_exception_transporter': '过滤非专享骑士',
    'filter_special_order_transporter': '专享过滤手头鲜花蛋糕单骑士',
    'filter_recommendation_score_transporter': '推荐指数过滤',
    'filter_assign_listen': '过滤专享订单听单骑士',
    'filter_order_cancelled_transporter': '过滤取消过该订单的骑士',
    'filter_short_assign_interval_new_transporter': '过滤上次派单间隔过短的新骑士',
    'filter_total_cargo_weight': '过滤达到最大接单重量的骑士',
    'filter_mcdonald_direct_order_transporter': '过滤麦当劳直送订单',
    'filter_assurance_order_limit_transporter_inshop_assign': '过滤达到最大兜底单量的骑士',
    'filter_same_way_score_inshop_assign': '过滤不顺路的骑士',
    'filter_human_feeling_rule_inshop_assign': '过滤不顺路的骑士',
    'filter_same_way_score_v2_inshop_assign': '过滤不顺路的骑士',
    'filter_same_way_score': '过滤不顺路的骑士',
    'filter_dispatch_same_way_score': '过滤不顺路的骑士',
    'filter_delay_transporter': '过滤派单后可能超时骑士',
    'filter_accept_task_validate': 'task接单权限校验',
    'filter_coronavirus_detect_order_transporter': '要求核酸检测订单过滤未上传核酸检测骑士',
    'filter_assign_process': '过滤专享派单过程中骑士',
    'filter_not_passed_offline_training_transporter': '过滤未通过实地培训骑士',
    'filter_positive_limit_order_scope_inshop_assign': '过滤非正向圈定范围订单',
    'filter_negative_limit_order_scope_inshop_assign': '过滤非反向圈定范围订单',
    'filter_integral_task_inshop_assign': '过滤未到兜底时间的订单',
    'filter_long_waiting_time_transporter_inshop_sam': '过滤山姆等单时间超过20分钟的骑士',
    'filter_unmanned_vehicle_inshop_assign': '未开启无人车派单门店组过滤无人车',
    'filter_common_transporter_by_receiver_phone': '[灰度逻辑]无人车过滤收货人手机号未匹配的订单',
    'filter_virtual_phone_number_order_inshop_assign': '无人车派单过滤带有虚拟手机号订单',
    'filter_different_aoi_order_inshop_assign': '无人车派单停靠点不匹配过滤',
    'filter_limit_single_expect_finish_time_inshop_assign': '无人车送达波次时间限制过滤',
    'filter_common_transporter_on_grab_order_inshop_assign': '抢单门店组无人车派单过滤正常骑士',
    'filter_long_trans_line_distance_transporter_inshop_assign': '过滤取货直线距离超过10km的骑士',
    'filter_stacked_supplier_order_inshop_assign': '配置骑士分组的骑士过滤非绑定门店订单',
    'filter_cross_intersect_order': '过滤跨越障碍物的骑士',
    'filter_cross_intersect_order_v2': '过滤跨越障碍物的骑士',
    'filter_supplier_order_num': '过滤低密度区域派单',
    'filter_not_grid_transporter': '网格派单过滤非网格骑士',
    'filter_test_grid_transporter': '非网格派单过滤网格骑士',
    'filter_ahead_assign': '限制提前派单',
    'filter_coincide_task_inshop_assign': '已接订单不再派',
    'filter_coordinate_error_with_sdktime': '坐标漂移过滤',
    'filter_out_grid_circle_order': '网格派单过滤出圈订单',
    'filter_limit_batch_number_inshop_assign': '无人车派单班次过滤(15min每班次)',
    'filter_limit_region_transporter_first_order_must_be_limit_order_inshop_assign': '片区绑定骑士限定首单限定（如有疑问咨询总部运营）',
    'filter_limit_region_transporter_inshop_assign': '绑定骑士路区的订单过滤非绑定骑士',
    'filter_cross_intersect_order_by_supplier_address': '发货地址跨越障碍物过滤',
    'filter_high_pressure_value_not_central_order': '高压力情况下过滤周边门店订单',
    'filter_mcdonald_order_limit_inshop_assign': '麦当劳品牌维度背单上限限制',
    'filter_special_order_transporter_grid': '过滤手头鲜花蛋糕单骑士',
    'filter_delay_transporter_grid': '过滤派单后可能超时骑士',
    'filter_actual_pick_up_distance_grid_assign': '取货距离远过滤',
    'filter_same_way_score_grid': '过滤不顺路的骑士',
    'filter_human_feeling_rule_grid_assign': '过滤不顺路的骑士',
    'filter_weighted_human_feeling_and_same_way_grid_assign': '过滤不顺路的骑士',
    'filter_same_way_score_multi_recall_grid_assign': '过滤不顺路的骑士',
    'filter_same_way_score_v2_grid_assign': '过滤不顺路的骑士',
    'filter_not_assign_crowdsourcing_transporter': '自由派单订单过滤非自由派单骑士',
    'filter_not_assign_transporter': '过滤未开启自动抢单开关的骑士',
    'filter_grid_process': '过滤众包派单过程中骑士',
    'filter_stacked_supplier_hold_inshop_assign': '中心门店hold单时间过滤商圈骑士',
    'filter_opposite_stop_order_unmanned_vehicle': '无人车互斥停靠点过滤',
    'filter_distance_preference_assign_crowdsourcing': '距离偏好过滤',
    'filter_low_order_density_area': '限制低密度区域派单',
    'filter_low_efficiency_order': '限制低性价比订单',
    'filter_cargo_weight_assign': '派单重量过滤',
    'filter_overweight_single_order_inshop_assign': '单笔订单超重过滤',
    'filter_onhands_num_assign_crowdsourcing': '骑士接单上限过滤',
    'filter_not_car_transporter_grid': '众包派单非四轮车骑士过滤',
    'filter_supplier_set_order_limit_inshop_assign': '门店集合背单上限过滤',
    'filter_coronavirus_detect_order_transporter': '要求电子通行证/核酸检测订单过滤未上传电子通行证/核酸检测骑士',
    'filter_supplier_order_limit_inshop_assign': '门店每日背单上限过滤',
    'filter_not_car_transporter': '四轮车订单过滤非四轮车骑士',
    'filter_order_not_in_unmanned_vehicle_stop_self': '过滤自身不在无人车停靠点的订单',
    'filter_order_not_in_unmanned_vehicle_stop_other': '过滤不可拆合单中其它订单不在无人车停靠点的订单',
    'filter_stop_count_limit': '过滤超出停靠点数限制的订单',
    'filter_inshop_supplier_group_with_special_order': '过滤门店组剔除的特殊类型订单',
    'filter_not_open_push_transporter': '过滤未开工骑士',
    'filter_long_location_interval_transporter_inshop_assign': '过滤10分钟未更新坐标的骑士',
    'filter_crest_low_value_order': '高峰期过滤低价单',
    'filter_different_region_of_task': '合单跨路区(不生效)',
    'filter_transporter_auth_validate_inshop_assign': '运力分层规则过滤',
    'filter_car_transporter': '过滤四轮车骑士',
    'filter_weight_by_order_labels_inshop_assign': '订单超重溢出',
    'filter_delay_dispatch_jd_order_inshop_assign': '京超订单延迟派单',
    'filter_jd_supplier_set_order_limit_inshop_assign': '超过背单上限',
    'filter_overweight_task_inshop_assign': '过滤超重合单(后续会拆单派)',
    'filter_not_authorized_transporter_v2': '过滤没有此task接单权限的骑士',
    'filter_not_brand_auth_transporter': '过滤非品牌众包优先骑士',
    'filter_not_accept_validated_transporter': '过滤没有接单权限的骑士',
    'filter_not_authorized_transporter_v3': '过滤没有接单权限的骑士',
    'filter_risk_transporter': '过滤被封禁骑士',
    'filter_ahead_grid_assign': '提前派单过滤',
    'filter_ahead_vip_assign': '提前派单过滤',
    'filter_onhands_num_crowd_assign': '骑士手头单量较高',
    'filter_empty_onhands': '过滤空单骑士',
    '骑士不在队列中': '过滤离队和休息的骑士',
    '骑士休息或不在队列中': '过滤离队和休息的骑士',
    '该骑士正在配送单量已超过上限，请选择其他骑士': '过滤超过背单上限骑士',
    '该骑士非服务商签约骑士，无法接驻店订单': '驻店订单过滤非服务商签约骑士',
    '已达当前门店背单上限，不可接单，请更换其他门店订单': '已达当前门店背单上限',
    '超过兜底接单上限': '过滤超过最大兜底单量的骑士',
    '当前不符合接单要求，请稍后再试': '过滤没有接单权限的骑士',
    '已达到门店完成单上限，今日不可再接该门店订单': '门店每日背单上限过滤',
    '运单标签与骑士标签不匹配': '运单标签与骑士标签不匹配',
    '该骑士帐号涉嫌违规行为，帐号已被封禁': '过滤被封禁骑士',
    '该骑士未通过平台综合安全评估，无法在平台工作': '过滤未通过平台综合安全评估骑士',
    '此运单需骑士拥有健康证才可配送': '过滤无健康证骑士',
    '直送标签限制': '直送标签限制',
    '骑士保险协议未同意，已影响接单，请尽快查看并同意': '骑士保险协议未同意，已影响接单，请尽快查看并同意',
    'filter_transporter_brand_limit_inshop_assign': '品牌屏蔽骑士',
    'filter_weighted_human_feeling_and_same_way_inshop_assign': '不顺路过滤',
    'filter_same_way_score_multi_recall_inshop_assign': '不顺路过滤',
    'filter_deliver_delay_inshop_assign': '过滤送货超时的骑士',
    'filter_inshop_recommend_limited_order': '驻店推荐过滤排序靠后订单',
    'filter_same_way_score_multi_recall': '过滤不顺路的骑士',
    'filter_not_group_auth_transporter': '过滤非小队排班骑士',
    'filter_inshop_assign_process': '有更合适的骑士',
    'filter_dispatch_same_way_score_multi_recall': '过滤不顺路的骑士',
    'filter_resident_area': '常驻区域过滤',
    'filter_single_delivery_common_order_inshop_assign': '低效普通单延后派单',
    'filter_qzc_transporet_layer_not_match_transporter': '前置仓骑士和圈层不匹配过滤',
    'filter_inshop_assign_resident_city_control_group': '过滤个人版驻城对照组订单',
    'filter_inshop_assign_out_circle_order': '过滤门店组的圈外订单',
    'filter_inshop_assign_special_order': '过滤门店组配置的特殊订单',
    'filter_not_core_promise_order': '高峰期限制非核心强履约订单',
    'filter_crowd_assign_dada_pro_transporter_not_urgent_order': '达达Pro过滤非急送订单',
    'filter_crowd_assign_long_distance': '自由抢单过滤非急送订单远单',
    'filter_appointment_order_early_delivery': '驻店预约单限制提前送达',
    'filter_not_identity_transporter': '必达单过滤非小队排班骑士/品牌众包hold单',
    'filter_dispatch_same_way_score_v2': '过滤不顺路的骑士',
    'filter_dada_pro_transporter_special_order_number_crowd_assign': '达达pro蛋糕单派单限制',
    'filter_blacklist_transporter': '过滤小队派单黑名单骑手',
    'filter_delivery_delay_inshop_assign': '过滤配送超时风险高骑士',
    'filter_only_dada_pro_transporter_order_crowd_assign': '非达达pro不能派蛋糕单或者直送',
    'filter_same_way_score_v2_vip_assign': '过滤不顺路骑士',
    'get_nearby_transporter_filter_transporter': '骑士未开工',
    'filter_full_time_black_brand': '过滤全职骑士派单黑名单品牌订单',
    'filter_full_time_not_in_polygon_order': '全职骑士过滤收货点不在派单围栏内的订单',
    'filter_full_time_transporter': '全派全职骑士不能抢单',
    'filter_not_full_time_inshop_order': '非全职骑士过滤驻店未溢出订单',
    'filter_pick_up_duration_inshop_assign': '骑士到店等餐时长过长',
    'filter_special_transporter_with_special_label': '当前骑士不符合运力接单要求',
    'filter_full_time_high_pressure_long_distance_order': '高峰期全职骑士过滤远单',
    'filter_full_time_peek_time_supplier': '高峰期全职骑士过滤卡餐商户',
    'filter_full_time_transporter_outlier': '过滤不顺路骑士-离群点'
}

filter_step_list = [
'filter_not_full_time_inshop_order',
'filter_short_assign_interval_new_transporter',
'filter_car_transporter',
'filter_cargo_weight_assign',
'filter_assign_listen',
'filter_ranker_step_transporter',
'filter_coordinate_error_with_sdktime',
'filter_crowd_assign_transporter_low_price_order',
'filter_dada_pro_transporter_special_order_number_crowd_assign',
'filter_crowd_assign_long_distance',
'filter_full_time_peek_time_supplier',
'filter_onhands_num_crowd_assign',
'filter_distance_preference_assign_crowdsourcing',
'filter_assigned_transporter',
'get_nearby_transporter_filter_transporter',
'filter_test_grid_transporter',
'filter_full_time_transporter_outlier',
'filter_onhands_order_invalid_status',
'filter_not_accept_validated_transporter',
'filter_grid_process',
'filter_same_way_score_v2_grid_assign',
'filter_resident_area',
'filter_full_time_black_brand',
'filter_crowd_assign_dada_pro_transporter_not_urgent_order',
'filter_full_time_not_in_polygon_order',
'filter_special_order_transporter_grid',
'filter_crowd_assign_transporter_black_receiver_order',
'filter_ahead_grid_assign',
'filter_over_river_transporter',
'filter_not_identity_transporter',
'filter_not_brand_auth_transporter',
'filter_actual_pick_up_distance_grid_assign',
'filter_delay_transporter_grid',
'filter_accept_cost_status_error',
'filter_full_time_high_pressure_long_distance_order',
'filter_only_dada_pro_transporter_order_crowd_assign',
'filter_not_assign_transporter'
]

filter_list1 = []
# filter_list2 = []
# for filter_step in filter_step_list:
#     filter_res = filter_step_dict[filter_step]
#     filter_list1.append(filter_step)
#     filter_list2.append(filter_res)
# pd_res = pd.DataFrame({'filter_list1': filter_list1, 'filter_list2': filter_list2})
# pd_res.to_csv('filter_res.csv', index=False)


res = sorted(set(list([1, 3, 2])))
print(res)

